package ru.itis.raily01.helper;// Generated by Selenium IDE

import org.openqa.selenium.Dimension;
import ru.itis.raily01.ApplicationManager;

public class NavigationHelper extends HelperBase {
    public void OpenHomePage() {
        driver.get("https://jut.su/");
        driver.manage().window().setSize(new Dimension(911, 824));
    }

    public void openAccountPage() throws InterruptedException {
        driver.get("https://jut.su/user/Railyy/");
        Thread.sleep(2000);
    }

    private String baseUrl;

    public NavigationHelper(ApplicationManager manager, String baseUrl) {
        super(manager);
        this.baseUrl = baseUrl;
    }

}
